# Generated by Django 3.2.23 on 2024-02-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_date', models.CharField(max_length=225)),
                ('starting_time', models.CharField(max_length=225)),
                ('ending_date', models.CharField(max_length=225)),
                ('ending_time', models.CharField(max_length=225)),
                ('amount', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='parking_location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('latitude', models.CharField(max_length=225)),
                ('longitude', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('hname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('encode', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('latitude', models.CharField(max_length=225)),
                ('longitude', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scr_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_description', models.CharField(max_length=225)),
                ('slot_status', models.CharField(max_length=225)),
                ('qrcode', models.FileField(upload_to='')),
                ('aamount', models.CharField(max_length=225)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scr_app.parking_location')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=225)),
                ('mode_of_payment', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scr_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('solution', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scr_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scr_app.slot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scr_app.login'),
        ),
    ]
